spring:
   application:
      name: rest-service-swype
   ssl:
      enabled: false
   port: 8111
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
    lease:
      duration: 5
    register-with-eureka: true
    fetch-registry: true
         
feign:
   client:
      config:
         default:
            connect-timeout: 6000
            read-timeout: 6000
   httpclient:
      connection-timeout: 6000
      max-connections-per-route: 10
      
http:
   protocol: http
