spring:
  application:
    name: rest-service-client
server:
   port: 8777
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
    lease:
      duration: 5
    register-with-eureka: true
    fetch-registry: true
     
feign:
   httpclient:
      max-connections: 15
      connection-timeout: 60000
   client:
      config:
         default:
            connect-timeout: 60000
            read-timeout: 60000

      
http:
   protocol: http